---
configure_dotfiles: true
configure_terminal: true
configure_osx: true
configure_ohmyzsh: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: ["Launchpad", "TV", "Podcasts", "App Store", "Reminders", "Notes", "Freeform", "Siri", "Music", "Facetime", "Photos", "Messages", "Mail"]
dockitems_persist: ["Firefox", "Visual Studio Code", "Terminal"]
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5


dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_repo_version: master # Replace with your default branch
dotfiles_files:
  - .zshrc
  - .gitignore
  - .osx

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - gh
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - nmap
  - node
  - pngpaste
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - pipx
  - uv
  - r
  - qgis-plugin-grass

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - google-chrome
  - slack
  - zoom
  - visual-studio-code
  - qgis
  - rstudio
  - postman
  - betterdisplay

# See `geerlingguy.mac.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
  - mlflow
  - dvc[s3]
  - cookiecutter
  - locust
  - poethepoet
  - poetry
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
